#!/bin/bash

required_snaps=("frogsquash" "gnome-2048" "gnome-chess" "gnome-dictionary" "gnome-nibbles" "gnome-weather" "iagno" "mc-installer" "quadrapassel" "snap-store" "spotify" "vlc" "zoom-client")
installed_snaps=(`snap list |grep -v Name | awk '{print $1}' | sort -u`)
missing_snaps=() 
failed=0

echo "Doing a final check to validate the automated install..."

echo "Checking for required snaps..."
for s in ${required_snaps[@]}
do
    if printf '%s\0' "${installed_snaps[@]}" | grep -qwz $s
    then
        continue
    else
        missing_snaps+=(${s})
    fi
done

if [ ${#missing_snaps[@]} -gt 0 ]
then
    echo "${#missing_snaps[@]} required snaps are not installed"
    echo "Missing snaps: ${missing_snaps[@]}"
    failed=1
#else
    #echo "All required snaps are installed"
fi

echo "Verifying the kramden-overrides package is installed..."
if ! dpkg -l |grep kramden-overrides 2>&1 >/dev/null
then
	echo "kramden-overrides is not installed"
	failed=1
fi

echo "Verifying crash report prompting is disabled..."
if grep enabled=1 /etc/default/apport 2>&1 >/dev/null
then
	echo "Apport is enabled"
	failed=1
fi

echo "Verifying unnecessary files have been cleaned up..."
if [ -f /etc/apt/trusted.gpg.d/custom-iso-key.gpg ]
then
    echo "custom iso key installed, should be removed"
    failed=1
fi

if [ $failed -gt 0 ]
then
    echo "Final installation verification has failed"
    exit 1
else
    echo "Final installation verification passed!"
fi
