name: Publish PPA kramden-test
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 1
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Prepare build
      run: |
        sudo apt-get install -y dpkg-dev rsync
        VERSION=$(dpkg-parsechangelog -S Version|awk -F "-" '{print $1}')
        mkdir -p ${{ github.workspace }}/artifacts/kramden-overrides-$VERSION
        rsync -r --exclude=.git --exclude=.github --exclude=artifacts . ${{ github.workspace }}/artifacts/kramden-overrides-$VERSION/
    - name: Publish build
      uses: yuezk/publish-ppa-package@main
      with:
        repository: 'ppa:kramden-team/kramden-test'
        gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
        series: "noble"
        tarball: publish-ppa/kramden-overrides-*/.build/tarball/*.tar.gz
        debian_dir: publish-ppa/kramden-overrides-*/.build/debian
        deb_email: "ken@vandine.org"
        deb_fullname: "Ken VanDine"
